/* soapH.h
   Generated by gSOAP 2.8.21 from meteo.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_std__string(soap, data),0) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetCitiesByCountryResponse
#define SOAP_TYPE__ns1__GetCitiesByCountryResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetCitiesByCountryResponse(struct soap*, const char*, int, const _ns1__GetCitiesByCountryResponse *, const char*);
SOAP_FMAC3 _ns1__GetCitiesByCountryResponse * SOAP_FMAC4 soap_in__ns1__GetCitiesByCountryResponse(struct soap*, const char*, _ns1__GetCitiesByCountryResponse *, const char*);

#ifndef soap_write__ns1__GetCitiesByCountryResponse
#define soap_write__ns1__GetCitiesByCountryResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:GetCitiesByCountryResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetCitiesByCountryResponse * SOAP_FMAC4 soap_get__ns1__GetCitiesByCountryResponse(struct soap*, _ns1__GetCitiesByCountryResponse *, const char*, const char*);

#ifndef soap_read__ns1__GetCitiesByCountryResponse
#define soap_read__ns1__GetCitiesByCountryResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetCitiesByCountryResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__GetCitiesByCountryResponse * SOAP_FMAC2 soap_instantiate__ns1__GetCitiesByCountryResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__GetCitiesByCountryResponse * soap_new__ns1__GetCitiesByCountryResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__GetCitiesByCountryResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__GetCitiesByCountryResponse * soap_new_req__ns1__GetCitiesByCountryResponse(struct soap *soap) { _ns1__GetCitiesByCountryResponse *_p = soap_instantiate__ns1__GetCitiesByCountryResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__GetCitiesByCountryResponse * soap_new_set__ns1__GetCitiesByCountryResponse(struct soap *soap, std::string *GetCitiesByCountryResult) { _ns1__GetCitiesByCountryResponse *_p = soap_instantiate__ns1__GetCitiesByCountryResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__GetCitiesByCountryResponse::GetCitiesByCountryResult = GetCitiesByCountryResult; } return _p; }

inline void soap_delete__ns1__GetCitiesByCountryResponse(struct soap *soap, _ns1__GetCitiesByCountryResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetCitiesByCountryResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetCitiesByCountry
#define SOAP_TYPE__ns1__GetCitiesByCountry (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetCitiesByCountry(struct soap*, const char*, int, const _ns1__GetCitiesByCountry *, const char*);
SOAP_FMAC3 _ns1__GetCitiesByCountry * SOAP_FMAC4 soap_in__ns1__GetCitiesByCountry(struct soap*, const char*, _ns1__GetCitiesByCountry *, const char*);

#ifndef soap_write__ns1__GetCitiesByCountry
#define soap_write__ns1__GetCitiesByCountry(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:GetCitiesByCountry", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetCitiesByCountry * SOAP_FMAC4 soap_get__ns1__GetCitiesByCountry(struct soap*, _ns1__GetCitiesByCountry *, const char*, const char*);

#ifndef soap_read__ns1__GetCitiesByCountry
#define soap_read__ns1__GetCitiesByCountry(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetCitiesByCountry(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__GetCitiesByCountry * SOAP_FMAC2 soap_instantiate__ns1__GetCitiesByCountry(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__GetCitiesByCountry * soap_new__ns1__GetCitiesByCountry(struct soap *soap, int n = -1) { return soap_instantiate__ns1__GetCitiesByCountry(soap, n, NULL, NULL, NULL); }

inline _ns1__GetCitiesByCountry * soap_new_req__ns1__GetCitiesByCountry(struct soap *soap) { _ns1__GetCitiesByCountry *_p = soap_instantiate__ns1__GetCitiesByCountry(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__GetCitiesByCountry * soap_new_set__ns1__GetCitiesByCountry(struct soap *soap, std::string *CountryName) { _ns1__GetCitiesByCountry *_p = soap_instantiate__ns1__GetCitiesByCountry(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__GetCitiesByCountry::CountryName = CountryName; } return _p; }

inline void soap_delete__ns1__GetCitiesByCountry(struct soap *soap, _ns1__GetCitiesByCountry *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetCitiesByCountry(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetWeatherResponse
#define SOAP_TYPE__ns1__GetWeatherResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetWeatherResponse(struct soap*, const char*, int, const _ns1__GetWeatherResponse *, const char*);
SOAP_FMAC3 _ns1__GetWeatherResponse * SOAP_FMAC4 soap_in__ns1__GetWeatherResponse(struct soap*, const char*, _ns1__GetWeatherResponse *, const char*);

#ifndef soap_write__ns1__GetWeatherResponse
#define soap_write__ns1__GetWeatherResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:GetWeatherResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetWeatherResponse * SOAP_FMAC4 soap_get__ns1__GetWeatherResponse(struct soap*, _ns1__GetWeatherResponse *, const char*, const char*);

#ifndef soap_read__ns1__GetWeatherResponse
#define soap_read__ns1__GetWeatherResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetWeatherResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__GetWeatherResponse * SOAP_FMAC2 soap_instantiate__ns1__GetWeatherResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__GetWeatherResponse * soap_new__ns1__GetWeatherResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__GetWeatherResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__GetWeatherResponse * soap_new_req__ns1__GetWeatherResponse(struct soap *soap) { _ns1__GetWeatherResponse *_p = soap_instantiate__ns1__GetWeatherResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__GetWeatherResponse * soap_new_set__ns1__GetWeatherResponse(struct soap *soap, std::string *GetWeatherResult) { _ns1__GetWeatherResponse *_p = soap_instantiate__ns1__GetWeatherResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__GetWeatherResponse::GetWeatherResult = GetWeatherResult; } return _p; }

inline void soap_delete__ns1__GetWeatherResponse(struct soap *soap, _ns1__GetWeatherResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetWeatherResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetWeather
#define SOAP_TYPE__ns1__GetWeather (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetWeather(struct soap*, const char*, int, const _ns1__GetWeather *, const char*);
SOAP_FMAC3 _ns1__GetWeather * SOAP_FMAC4 soap_in__ns1__GetWeather(struct soap*, const char*, _ns1__GetWeather *, const char*);

#ifndef soap_write__ns1__GetWeather
#define soap_write__ns1__GetWeather(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:GetWeather", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetWeather * SOAP_FMAC4 soap_get__ns1__GetWeather(struct soap*, _ns1__GetWeather *, const char*, const char*);

#ifndef soap_read__ns1__GetWeather
#define soap_read__ns1__GetWeather(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetWeather(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__GetWeather * SOAP_FMAC2 soap_instantiate__ns1__GetWeather(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__GetWeather * soap_new__ns1__GetWeather(struct soap *soap, int n = -1) { return soap_instantiate__ns1__GetWeather(soap, n, NULL, NULL, NULL); }

inline _ns1__GetWeather * soap_new_req__ns1__GetWeather(struct soap *soap) { _ns1__GetWeather *_p = soap_instantiate__ns1__GetWeather(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__GetWeather * soap_new_set__ns1__GetWeather(struct soap *soap, std::string *CityName, std::string *CountryName) { _ns1__GetWeather *_p = soap_instantiate__ns1__GetWeather(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__GetWeather::CityName = CityName; _p->_ns1__GetWeather::CountryName = CountryName; } return _p; }

inline void soap_delete__ns1__GetWeather(struct soap *soap, _ns1__GetWeather *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetWeather(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__GetCitiesByCountry_
#define SOAP_TYPE___ns1__GetCitiesByCountry_ (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetCitiesByCountry_(struct soap*, struct __ns1__GetCitiesByCountry_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetCitiesByCountry_(struct soap*, const struct __ns1__GetCitiesByCountry_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetCitiesByCountry_(struct soap*, const char*, int, const struct __ns1__GetCitiesByCountry_ *, const char*);
SOAP_FMAC3 struct __ns1__GetCitiesByCountry_ * SOAP_FMAC4 soap_in___ns1__GetCitiesByCountry_(struct soap*, const char*, struct __ns1__GetCitiesByCountry_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetCitiesByCountry_(struct soap*, const struct __ns1__GetCitiesByCountry_ *, const char*, const char*);

#ifndef soap_write___ns1__GetCitiesByCountry_
#define soap_write___ns1__GetCitiesByCountry_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__GetCitiesByCountry_(soap, data),0) || soap_put___ns1__GetCitiesByCountry_(soap, data, "-ns1:GetCitiesByCountry", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__GetCitiesByCountry_ * SOAP_FMAC4 soap_get___ns1__GetCitiesByCountry_(struct soap*, struct __ns1__GetCitiesByCountry_ *, const char*, const char*);

#ifndef soap_read___ns1__GetCitiesByCountry_
#define soap_read___ns1__GetCitiesByCountry_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetCitiesByCountry_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__GetCitiesByCountry_ * SOAP_FMAC2 soap_instantiate___ns1__GetCitiesByCountry_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__GetCitiesByCountry_ * soap_new___ns1__GetCitiesByCountry_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__GetCitiesByCountry_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__GetCitiesByCountry_ * soap_new_req___ns1__GetCitiesByCountry_(struct soap *soap) { struct __ns1__GetCitiesByCountry_ *_p = soap_instantiate___ns1__GetCitiesByCountry_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetCitiesByCountry_(soap, _p); } return _p; }

inline struct __ns1__GetCitiesByCountry_ * soap_new_set___ns1__GetCitiesByCountry_(struct soap *soap, _ns1__GetCitiesByCountry *ns1__GetCitiesByCountry) { struct __ns1__GetCitiesByCountry_ *_p = soap_instantiate___ns1__GetCitiesByCountry_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetCitiesByCountry_(soap, _p); _p->ns1__GetCitiesByCountry = ns1__GetCitiesByCountry; } return _p; }

inline void soap_delete___ns1__GetCitiesByCountry_(struct soap *soap, struct __ns1__GetCitiesByCountry_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetCitiesByCountry_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetWeather_
#define SOAP_TYPE___ns1__GetWeather_ (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetWeather_(struct soap*, struct __ns1__GetWeather_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetWeather_(struct soap*, const struct __ns1__GetWeather_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetWeather_(struct soap*, const char*, int, const struct __ns1__GetWeather_ *, const char*);
SOAP_FMAC3 struct __ns1__GetWeather_ * SOAP_FMAC4 soap_in___ns1__GetWeather_(struct soap*, const char*, struct __ns1__GetWeather_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetWeather_(struct soap*, const struct __ns1__GetWeather_ *, const char*, const char*);

#ifndef soap_write___ns1__GetWeather_
#define soap_write___ns1__GetWeather_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__GetWeather_(soap, data),0) || soap_put___ns1__GetWeather_(soap, data, "-ns1:GetWeather", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__GetWeather_ * SOAP_FMAC4 soap_get___ns1__GetWeather_(struct soap*, struct __ns1__GetWeather_ *, const char*, const char*);

#ifndef soap_read___ns1__GetWeather_
#define soap_read___ns1__GetWeather_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetWeather_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__GetWeather_ * SOAP_FMAC2 soap_instantiate___ns1__GetWeather_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__GetWeather_ * soap_new___ns1__GetWeather_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__GetWeather_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__GetWeather_ * soap_new_req___ns1__GetWeather_(struct soap *soap) { struct __ns1__GetWeather_ *_p = soap_instantiate___ns1__GetWeather_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetWeather_(soap, _p); } return _p; }

inline struct __ns1__GetWeather_ * soap_new_set___ns1__GetWeather_(struct soap *soap, _ns1__GetWeather *ns1__GetWeather) { struct __ns1__GetWeather_ *_p = soap_instantiate___ns1__GetWeather_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetWeather_(soap, _p); _p->ns1__GetWeather = ns1__GetWeather; } return _p; }

inline void soap_delete___ns1__GetWeather_(struct soap *soap, struct __ns1__GetWeather_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetWeather_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetCitiesByCountry
#define SOAP_TYPE___ns1__GetCitiesByCountry (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetCitiesByCountry(struct soap*, struct __ns1__GetCitiesByCountry *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetCitiesByCountry(struct soap*, const struct __ns1__GetCitiesByCountry *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetCitiesByCountry(struct soap*, const char*, int, const struct __ns1__GetCitiesByCountry *, const char*);
SOAP_FMAC3 struct __ns1__GetCitiesByCountry * SOAP_FMAC4 soap_in___ns1__GetCitiesByCountry(struct soap*, const char*, struct __ns1__GetCitiesByCountry *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetCitiesByCountry(struct soap*, const struct __ns1__GetCitiesByCountry *, const char*, const char*);

#ifndef soap_write___ns1__GetCitiesByCountry
#define soap_write___ns1__GetCitiesByCountry(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__GetCitiesByCountry(soap, data),0) || soap_put___ns1__GetCitiesByCountry(soap, data, "-ns1:GetCitiesByCountry", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__GetCitiesByCountry * SOAP_FMAC4 soap_get___ns1__GetCitiesByCountry(struct soap*, struct __ns1__GetCitiesByCountry *, const char*, const char*);

#ifndef soap_read___ns1__GetCitiesByCountry
#define soap_read___ns1__GetCitiesByCountry(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetCitiesByCountry(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__GetCitiesByCountry * SOAP_FMAC2 soap_instantiate___ns1__GetCitiesByCountry(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__GetCitiesByCountry * soap_new___ns1__GetCitiesByCountry(struct soap *soap, int n = -1) { return soap_instantiate___ns1__GetCitiesByCountry(soap, n, NULL, NULL, NULL); }

inline struct __ns1__GetCitiesByCountry * soap_new_req___ns1__GetCitiesByCountry(struct soap *soap) { struct __ns1__GetCitiesByCountry *_p = soap_instantiate___ns1__GetCitiesByCountry(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetCitiesByCountry(soap, _p); } return _p; }

inline struct __ns1__GetCitiesByCountry * soap_new_set___ns1__GetCitiesByCountry(struct soap *soap, _ns1__GetCitiesByCountry *ns1__GetCitiesByCountry) { struct __ns1__GetCitiesByCountry *_p = soap_instantiate___ns1__GetCitiesByCountry(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetCitiesByCountry(soap, _p); _p->ns1__GetCitiesByCountry = ns1__GetCitiesByCountry; } return _p; }

inline void soap_delete___ns1__GetCitiesByCountry(struct soap *soap, struct __ns1__GetCitiesByCountry *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetCitiesByCountry(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetWeather
#define SOAP_TYPE___ns1__GetWeather (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetWeather(struct soap*, struct __ns1__GetWeather *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetWeather(struct soap*, const struct __ns1__GetWeather *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetWeather(struct soap*, const char*, int, const struct __ns1__GetWeather *, const char*);
SOAP_FMAC3 struct __ns1__GetWeather * SOAP_FMAC4 soap_in___ns1__GetWeather(struct soap*, const char*, struct __ns1__GetWeather *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetWeather(struct soap*, const struct __ns1__GetWeather *, const char*, const char*);

#ifndef soap_write___ns1__GetWeather
#define soap_write___ns1__GetWeather(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__GetWeather(soap, data),0) || soap_put___ns1__GetWeather(soap, data, "-ns1:GetWeather", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__GetWeather * SOAP_FMAC4 soap_get___ns1__GetWeather(struct soap*, struct __ns1__GetWeather *, const char*, const char*);

#ifndef soap_read___ns1__GetWeather
#define soap_read___ns1__GetWeather(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetWeather(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__GetWeather * SOAP_FMAC2 soap_instantiate___ns1__GetWeather(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__GetWeather * soap_new___ns1__GetWeather(struct soap *soap, int n = -1) { return soap_instantiate___ns1__GetWeather(soap, n, NULL, NULL, NULL); }

inline struct __ns1__GetWeather * soap_new_req___ns1__GetWeather(struct soap *soap) { struct __ns1__GetWeather *_p = soap_instantiate___ns1__GetWeather(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetWeather(soap, _p); } return _p; }

inline struct __ns1__GetWeather * soap_new_set___ns1__GetWeather(struct soap *soap, _ns1__GetWeather *ns1__GetWeather) { struct __ns1__GetWeather *_p = soap_instantiate___ns1__GetWeather(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetWeather(soap, _p); _p->ns1__GetWeather = ns1__GetWeather; } return _p; }

inline void soap_delete___ns1__GetWeather(struct soap *soap, struct __ns1__GetWeather *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetWeather(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetCitiesByCountry
#define SOAP_TYPE_PointerTo_ns1__GetCitiesByCountry (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetCitiesByCountry(struct soap*, _ns1__GetCitiesByCountry *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetCitiesByCountry(struct soap*, const char *, int, _ns1__GetCitiesByCountry *const*, const char *);
SOAP_FMAC3 _ns1__GetCitiesByCountry ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetCitiesByCountry(struct soap*, const char*, _ns1__GetCitiesByCountry **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetCitiesByCountry(struct soap*, _ns1__GetCitiesByCountry *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__GetCitiesByCountry
#define soap_write_PointerTo_ns1__GetCitiesByCountry(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetCitiesByCountry(soap, data),0) || soap_put_PointerTo_ns1__GetCitiesByCountry(soap, data, "ns1:GetCitiesByCountry", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetCitiesByCountry ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetCitiesByCountry(struct soap*, _ns1__GetCitiesByCountry **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetCitiesByCountry
#define soap_read_PointerTo_ns1__GetCitiesByCountry(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetCitiesByCountry(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__GetWeather
#define SOAP_TYPE_PointerTo_ns1__GetWeather (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetWeather(struct soap*, _ns1__GetWeather *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetWeather(struct soap*, const char *, int, _ns1__GetWeather *const*, const char *);
SOAP_FMAC3 _ns1__GetWeather ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetWeather(struct soap*, const char*, _ns1__GetWeather **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetWeather(struct soap*, _ns1__GetWeather *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__GetWeather
#define soap_write_PointerTo_ns1__GetWeather(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetWeather(soap, data),0) || soap_put_PointerTo_ns1__GetWeather(soap, data, "ns1:GetWeather", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetWeather ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetWeather(struct soap*, _ns1__GetWeather **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetWeather
#define soap_read_PointerTo_ns1__GetWeather(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetWeather(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data),0) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
